### ISSUE TITLE
Can't imbue scepter with create sponge even when wit level is 1

### ISSUE THREAD

**Issue by jaredniegas** [fzzyhmstrs/ai#27] opened 2022-07-27 04:01 UTC
The book of lore says wit level needs to be 1 but the scepter I have is already level 1.
Is this a bug?

**Comment by fzzyhmstrs** [comment] 2022-07-27 11:25
What version of the mod are you using?

**Comment by fzzyhmstrs** [comment] 2022-07-27 12:47
I can't replicate this issue in the latest 1.19 or 1.18.2 versions, so if you aren't running the latest try that. I tried with several different spells (including create sponge) and all worked. Here's summon chicken working:

![image](https://user-images.githubusercontent.com/72876796/181250154-31e3eb3a-4b5a-43ce-8c84-c02a356704a8.png)

![image](https://user-images.githubusercontent.com/72876796/181250193-401ec3f7-d01b-4497-b1e1-65ce6156a3ba.png)

**Comment by K0mmunist** [comment] 2022-07-27 18:55
I have a similar issue. I can't imbue any scepter even if it requires level 1 of F/G/W in survival. But after changing gamemode to creative fixes it. Also, this bug happens only to scepter imbuing, everything else works fine.
![изображение](https://user-images.githubusercontent.com/82029862/181348671-f11d662c-0823-497c-b150-fed0a59d4b74.png)
![изображение](https://user-images.githubusercontent.com/82029862/181348786-51dd836a-4567-4da0-b116-2c49749ae5e8.png)
(mend was added in creative)
Minecraft version: 1.18.2 / Quilt 0.17.1-beta.6
Mod version: 1.18.2-22
Also, i have another issue with this mod. Ores don't have color with draconic vision. but they had it not so long ago.

**Comment by fzzyhmstrs** [comment] 2022-07-27 18:58
Just for clarity, you do have three XP levels right?

Maybe it's some interaction with Quilt if you do have them.

The ore colors might be an issue with the embedded library that I found and fixed just yesterday (not released yet)

**Comment by K0mmunist** [comment] 2022-07-27 19:27
Well, about scepters. Now it works with chicken after interaction with altar of expirience. When i didn't have one scepters didn't want to imbue. Don't know why, but it works now. Maybe full reload of XP thruogh altar, maybe updating quilt

Found older screenshots of this. XP wasn't the problem, i think. 
![изображение](https://user-images.githubusercontent.com/82029862/181355427-a05a82e3-9282-4c3c-9007-09367667fc43.png)
![изображение](https://user-images.githubusercontent.com/82029862/181355529-af2482e3-ec98-4458-b160-4680a010817d.png)

**Comment by fzzyhmstrs** [comment] 2022-07-27 19:46
Interesting. The Altar doesn't interact with the Imbuing Table in any direct way, so it either nudged Quilt into monitoring something it wasn't previously, or the update on Quilt did it. I'm assuming to 0.17.1 which just came out today.

Maybe this weekend I'll make some quilt instances and mess around with it a bit. Glad it's working now for you at least!

**Comment by K0mmunist** [comment] 2022-07-28 05:46
After some tests, i can say that Quilt wasn't the problem. I have the same issue in Fabric. Reason why summoning chicken worked was upgrading grace on my scepter to level 5. Everything that requires fury or wit still doesn't work.

Screenshots from Quilt:
![изображение](https://user-images.githubusercontent.com/82029862/181429203-55ba61d2-6c8d-4f31-8de0-f00b2bba54a1.png)
![изображение](https://user-images.githubusercontent.com/82029862/181429293-840080fa-74b6-451a-b961-e03c6ab9241c.png)
![изображение](https://user-images.githubusercontent.com/82029862/181429448-79bf4de6-2418-4f04-bf40-34a30d11fd90.png)

and one from Fabric: 
![изображение](https://user-images.githubusercontent.com/82029862/181429527-226a486a-bcc9-4d24-acea-dc378343810d.png)

Also i use 244 mods (as main menu says), so that can be the reason

**Comment by fzzyhmstrs** [comment] 2022-07-28 10:38
Extremely Strange. I don't know what mod could be interacting with that function.

You mentioned that you've had some behavior change from earlier to now. What version of AI did you start with? And did you have that same Scepter/Chicken Book/Table from a previous version? Maybe there's some strange interaction between updates I'm not currently aware of.

**Comment by K0mmunist** [comment] 2022-07-28 13:11
First version of AI that i used was 1.18.2-21. I'm not sure in which version i got this scepter, only thing i remember is that i found it generated in some structure (and 2 more which also didn't work) 

All mods i have were added by me, i don't use any modpacks. But i can upload archive with all mods to somewhere

Video from new world:

https://user-images.githubusercontent.com/82029862/181513323-f1e5d1d2-7723-4c9c-83d9-94da4481bea3.mp4

(sorry for quality)

**Comment by fzzyhmstrs** [comment] 2022-07-28 15:09
Making some progress, finally! I can replicate the bug now in 1.18.2-21 and beyond. For reasons that I will now be investigating, non-crafted scepters don't have all the NBT they are supposed to, seen below from NBTExplorer (top one crafted, bottom one not). Will follow up soon; in the meantime, if you could please try crafting an Opaline Scepter and then checking Summon Chicken or Flamebolt or something simple, to hopefully backup my findings.

![image](https://user-images.githubusercontent.com/72876796/181572168-73e0da31-5e0e-4ed5-8e3a-082dcc08671b.png)

**Comment by K0mmunist** [comment] 2022-07-28 15:24
Oh, i tried crafting new scepter in new world and it really worked
![изображение](https://user-images.githubusercontent.com/82029862/181575988-0d2d2ece-6ede-4bf2-9023-2512753c79ea.png)

**Comment by fzzyhmstrs** [comment] 2022-07-28 17:46
Yes, the NBT "_lvl" and "_xp" tags not always attaching properly was the cause. [New versions are out](https://www.curseforge.com/minecraft/mc-mods/amethyst-imbuement/files) with a fix applied (among many other updates). Closing ticket. Reopen or submit a new one if any further issues on this subject come up.

**Closed by fzzyhmstrs** 2022-07-28 17:46 UTC
