### ISSUE TITLE
Incorrect mana cost and cooldown for fangs spells

### ISSUE THREAD

**Issue by IwasConfused** [fzzyhmstrs/ai#75] opened 2023-02-18 14:15 UTC
Sometimes the spells about fangs (Fangs, Fang Barrage etc. ) will ignore the cooldown and mana cost when casting, making it can be cast in an incredible speed.

**Comment by fzzyhmstrs** [comment] 2023-02-18 14:19
How do you replicate this? Just sometimes when casting normally? So far I have not been able to replicate this. The scepter uses the item cooldown feature that normal Minecraft uses for Ender Pearls and other vanilla items with cooldowns.

So far I've tried:
*  Simply trying to cast it over and over as fast as possible.
* Rapidly switching between spells after cast to try to trick it.

Neither of these attempts has replicated the problem for me. Are you in a multiplayer server environment?

**Comment by IwasConfused** [comment] 2023-02-18 14:58
> How do you replicate this? Just sometimes when casting normally? So far I have not been able to replicate this. The scepter uses the item cooldown feature that normal Minecraft uses for Ender Pearls and other vanilla items with cooldowns.
> 
> So far I've tried:
> 
> * Simply trying to cast it over and over as fast as possible.
> * Rapidly switching between spells after cast to try to trick it.
> 
> Neither of these attempts has replicated the problem for me. Are you in a multiplayer server environment?

![3NJJ6D{%{`ZB@%RNNS 22G5](https://user-images.githubusercontent.com/70762136/219872581-f08a2c0c-3444-4a12-a82d-cd2d8a0384ca.png)
This is the scepter I used at that time
This issue really only happens "sometimes", so it is difficult for me to replicate it, but it does exist, and other people have reported the same issue.

**Comment by IwasConfused** [comment] 2023-02-18 15:02
not multiplayer.

**Comment by fzzyhmstrs** [comment] 2023-02-18 15:11
Ok, thank you for the information. I will try to look for the issue and a solution, but it's hard if the issue isn't easy to replicate. Will do my best.

**Comment by fzzyhmstrs** [comment] 2023-02-18 15:16
Actually I may have found a potential situation to replicate it. Can you also check if you travel to below y=0 (in deepslate caves somewhere) does it start ignoring cooldown?

**Comment by IwasConfused** [comment] 2023-02-18 15:31
It seems so. I was casting Fang Barrage in an underground dungeon at that time. When I just travel to below y=0 again. it can be replicated

**Comment by fzzyhmstrs** [comment] 2023-02-20 13:36
Fixed in latest AI releases

**Closed by fzzyhmstrs** 2023-02-20 13:36 UTC
